### ISSUE TITLE
Can't get to work in Nuxt

### ISSUE THREAD

**Issue by devanflaherty** [dobromir-hristov/vue-vimeo-player#1]
Hey there,
This component looks great but I can't seem to get it to work in Nuxt.
I get an error of 'window undefined'.

I understand this snippet should help so it's only built in the client.

```
if (process.BROWSER_BUILD) {
  var vueVimeoPlayer = require('vue-vimeo-player')
}
```

But it's not rendering the component. I'm still new to Nuxt but was hoping maybe you could provide insight? If not feel free to close this!

Thanks.

**Comment by dobromir-hristov** [comment]
This is not related to vue-vimeo-player. You are on the right track, but I am not exactly sure how to go from there, as now you just imported the plugin. From there on you need to tell Vue to use it, or create a component manually. 
https://github.com/nuxt/nuxt.js/issues/414
https://github.com/egoist/vue-no-ssr - might help as well :)

**Comment by dobromir-hristov** [comment]
Nuxt support coming in next release with documentation.

**Comment by dobromir-hristov** [comment]
@devanflaherty check it out https://github.com/dobromir-hristov/vue-vimeo-player#usage-with-nuxtjs

**Comment by devanflaherty** [comment]
Thanks for the hard work man.
