### ISSUE TITLE
Update to latest Vue

### ISSUE THREAD

**Issue by liborvanek** [dobromir-hristov/vue-vimeo-player#10]
Hi, 
any chance of updating 'peerDependencies' to latest Vue version? I'd say, this is critical as there's security fix included.
Current version breaks Nuxt build, there's a conflict with vue-server-renderer.

**Comment by dobromir-hristov** [comment]
Peer deps are to be installed by the user explicitly, and at most show errors. 

I can update it no worries, but this should not be the cause of the break.

**Comment by liborvanek** [comment]
I'm not sure, but `yarn why vue` says:
```
=> Found "vue@2.5.16"
info Reasons this module exists
   - "vue-vimeo-player" depends on it
   - Hoisted from "vue-vimeo-player#vue"
```
And if I remove the dependency from vue-vimeo in yarn.lock, it starts working..

**Comment by dobromir-hristov** [comment]
Pushed.

**Comment by liborvanek** [comment]
Works. Thanks!
