### ISSUE TITLE
Invalid State Error...

### ISSUE THREAD

**Issue by matteboy99** [dobromir-hristov/vue-vimeo-player#12]
Hi,

Really easy to integrate with my Laravel app - videos loading and playing as they should.
However I'm getting a console error:
"InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable"

Have you come across this before? I need to hook into the players events but this seems to be stopping me.

![screen shot 2018-09-18 at 13 05 31](https://user-images.githubusercontent.com/16179868/45686160-957cff00-bb43-11e8-84cf-b47f4e120790.png)

Cheers

**Comment by dobromir-hristov** [comment]
I have not seen this. Check if your browser has some blockers or something. Firefox blocks some requests by default.

**Comment by matteboy99** [comment]
Thanks @dobromir-hristov . I'll look into that. I managed to hook the events - works really well!

Cheers

Matt

**Comment by dobromir-hristov** [comment]
If you need anything just ask.
