### ISSUE TITLE
:autoplay

### ISSUE THREAD

**Issue by Chemahin** [dobromir-hristov/vue-vimeo-player#14]
Hi everyone !) I use your component but have a problem. prop autoplay doesn't work ((( what am I doing wrong ?

<vimeo-player
ref="player"
:video-id="videoID"
@ready="onReady"
:autoplay="autoplay"
:player-height="height"
:player-width="width"
:loop="true">

<script> export default { data() { return { autoplay: true, videoID: '1', height: 1000, width: 1300, options: {}, playerReady: false } } thanks for the answer)

**Comment by dobromir-hristov** [comment]
If you are testing on a mobile device that will not work. Other than that, I dont see any problem in this working as expected.

Make a reproducible example on Codesandbox.io and come back so I can give feedback.

**Comment by Chemahin** [comment]
Thank you very much. I will check it now.
