### ISSUE TITLE
Width: 100% - Not working.

### ISSUE THREAD

**Issue by eckelarsson** [dobromir-hristov/vue-vimeo-player#15]
Please enable % in the width and height prop for the iframe width.

**Comment by dobromir-hristov** [comment]
Hey. From what I see, the Vimeo player API doesnt really support this fully. What you could do is, create a normal css wrapping class, that sets the iframe to 100%. You could even add some aspect ratio's helpers.

**Comment by mesaglam** [comment]
I just want to thank you for this work. Long live @dobromir-hristov !..

**Comment by eckelarsson** [comment]
Thank you both for the answer, solved it the same way @mesaglam should have commented that.

Sorry for the late comment @dobromir-hristov
