### ISSUE TITLE
Responsive Videos

### ISSUE THREAD

**Issue by delueg** [dobromir-hristov/vue-vimeo-player#16]
It should be possible to generate the embed without width and height attributes.

Described here -> https://help.vimeo.com/hc/en-us/articles/360000710167-Adjusting-the-size-of-the-embedded-player

**Comment by valjar** [comment]
Bump for interest

**Comment by dobromir-hristov** [comment]
This literally adds a 16/9 div around it. This can be totally done with CSS only. ![Responsive Iframes with One Great CSS Trick](https://blog.theodo.fr/2018/01/responsive-iframes-css-trick/)

**Comment by delueg** [comment]
That's not true.

I believe you meant this link, as your link is broken.

https://blog.theodo.fr/2018/01/responsive-iframes-css-trick/

He speaks there to remove width and height attributes to make it work.

Also to work with ! important css rule is not working in every Scenario.

**Comment by pjhile** [comment]
+1
