### ISSUE TITLE
error on refreshing browser

### ISSUE THREAD

**Issue by Timibadass** [dobromir-hristov/vue-vimeo-player#18]
Hi, the video player works fine until i refresh the page, then it throws this error

`You must pass either a valid element or a valid id.`

I am using it with nuxt.

**Comment by dobromir-hristov** [comment]
Please share some example code or repo so I can see the issue.

**Comment by Timibadass** [comment]
here's the part of my code that has to do with the player
`<vimeo-player class="videoplayer" ref="video" :video-id="video_id" :autoplay=true :player-width='playerWidth' :player-height="playerHeight"></vimeo-player>`

my data:
`data() {
    return {
      video_id: 'videoID',
      playerHeight: '',
      playerWidth: '',
    }
  }`

the playerHeight and playerWidth is set in methods on loading of the page.

**Comment by dobromir-hristov** [comment]
Something is preventing the player to mount. Are you using the no-ssr component in nuxt? Because it shouldn't be rendered on the server.

**Comment by Timibadass** [comment]
I thought the docs says using no-ssr is optional?. Thanks though, it helped me fix the bug

**Comment by anthonygore** [comment]
Not sure this should be closed, I think the docs should make it clear that the `ssr: false` option is not sufficient. Can add as PR if you need

**Comment by dobromir-hristov** [comment]
Should be fixed, thanks @anthonygore

**Comment by studiolathe** [comment]
Hi @dobromir-hristov

I am facing the same issue and error message when refreshing page in Nuxt. I am using the component inside a parent component which displays the video conditionally if a `video-id` is supplied via a prop (I have tried both `v-if` and `v-show`). See code below:

```
<div class="section-header-video__container" v-if="videoSrc">
  <client-only>
    <vimeo-player
      ref="player"
      :video-id="videoSrc"
      :controls="false"
      :autoplay="true"
      :loop="true"
      :options="videoOptions"
    />
  </client-only>
</div>
```

To be clear, the `video-id` is definitely being passed to the parent component and it works fine on first load but throws error on refresh. Any tips on solving?

Thanks!

**Comment by dobromir-hristov** [comment]
This is very odd. I don't see a reason why it should error

**Comment by studiolathe** [comment]
@dobromir-hristov I have just resolved the issue – it was seperate component causing a mounting error and in turn breaking the app.

Thanks for the great module!
