### ISSUE TITLE
how to know if component is "on focus"

### ISSUE THREAD

**Issue by AKUmajinn** [dobromir-hristov/vue-vimeo-player#19]
Hi, i try to search this option but i don't find it, if don't exist maybe can considerated added it in the future?, this will be usefull for make interactions like the buttons of player

**Comment by dobromir-hristov** [comment]
From what I saw, there is no way to track focus from the vimeo player itself. What you could do is manually track it with `<vimeo-player @focus.native="handleFocus" @blur.native="handleBlur"/>`

Even if we keep the state on the player, you still need to access it vie events, or a `$ref` depending on preference.

**Comment by AKUmajinn** [comment]
> From what I saw, there is no way to track focus from the vimeo player itself. What you could do is manually track it with `<vimeo-player @focus.native="handleFocus" @blur.native="handleBlur"/>`
> 
> Even if we keep the state on the player, you still need to access it vie events, or a `$ref` depending on preference.

I understand, i tried with @focus.native, but it does not work, it seems that the "focus" is lost when the content is an iframe (the focus moves in there) :(

thanks for the reply 😃
