### ISSUE TITLE
How can I get the current time of video?

### ISSUE THREAD

**Issue by walsh-dan** [dobromir-hristov/vue-vimeo-player#20]
I see `@timeupdate` firing every 250ms but cannot figure out how to get the actual timestamp. Any help?

``` 
 <vimeo-player ref="player" @timeupdate="updateCurrentTime"></vimeo-player>
```

```
methods: {
  updateCurrentTime() {
    console.log(currentTime) 
  }
}
```

**Comment by dobromir-hristov** [comment]
This is something for which you need to reach into the player instance.
```js
const time = await this.$refs.vimeo.player.getCurrentTime()
```
https://github.com/vimeo/player.js#getcurrenttime-promisenumber-error for more info.

**Comment by walsh-dan** [comment]
Thanks for your reply. I'm new to vue and still can't figure it out. Any other hints?

**Comment by dobromir-hristov** [comment]
Sorry, that is the way to do it. It is not a reactive property we can have on the component.

**Comment by walsh-dan** [comment]
No problem, thank you for your quick replies. I ended up using @vimeo/player and it works now

**Comment by dobromir-hristov** [comment]
That is literally what this plugin uses 😆 Glad you got it working.
