### ISSUE TITLE
getDuration

### ISSUE THREAD

**Issue by makerstorage** [dobromir-hristov/vue-vimeo-player#21]
Hi,

How can get the duration of the loaded video?
Vimeo API has a getDuration function

Regards

**Comment by dobromir-hristov** [comment]
use the player instance. Ints a bit convoluted but something like this.
`this.$refs.player.player.getDuration()` if you have a `ref="player"` on your component.

**Comment by makerstorage** [comment]
Thanks for the quick return. This is a JS question but
It sends back a promise. When I console.log the result I saw something like this

Promise {<pending>}
__proto__: Promise
[[PromiseStatus]]: "resolved"
[[PromiseValue]]: 8

How can I get the value of 8?

**Comment by dobromir-hristov** [comment]
resolve the promise? Use await or then. All methods of vimeo are asynx

**Comment by makerstorage** [comment]
this.$refs.player.player.getDuration()
                    .then(function(result) {
                      console.log (result);
                    })
solved my issue thanks alot
