### ISSUE TITLE
Cue Points

### ISSUE THREAD

**Issue by brjohnson4** [dobromir-hristov/vue-vimeo-player#22]
So how would you add cue points to a video, and then access the event when a cue point is reached?

**Comment by dobromir-hristov** [comment]
You can assign a cue point from the `player` property, accessing it via a `$refs.vimeo.player.addCuePoint()` -> [api reference](https://www.npmjs.com/package/@vimeo/player#addcuepointtime-number-data-object-promisestring-unsupportederrorrangeerrorerror)

Then the event will be emitted back via a `@cuepoint` event.
