### ISSUE TITLE
Use component without video-id

### ISSUE THREAD

**Issue by shusharin** [dobromir-hristov/vue-vimeo-player#24]
Hi! Some times, we need use player without video-id.

For example:
We have list of videos. When i click on image preview, player must:
`update(videoId)`
But, at this moment player not init, and we can't use 
`this.$refs.player.update(videoId)`
this.$refs.player - is null.

Another case:
We have input for video-id. When user set ID, we must load & show video.

Maybe we can set video-id id not required prop? 
Or, maybe we can add some prop like "empty-player" & video-id can be null?

**Comment by dobromir-hristov** [comment]
Just v-if when you have an id.
