### ISSUE TITLE
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by Hurtak** [dobromir-hristov/vue-vimeo-player#3]
Hi, I am using vue-vimeo-player with Nuxt and I am getting this error:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

Versions

```
  "dependencies": {
    "nuxt": "^1.0.0",
    "vue-vimeo-player": "0.0.6"
  },

```

nuxt.config.js

```

  plugins: [
    {
      // https://github.com/dobromir-hristov/vue-vimeo-player#usage-with-nuxtjs
      src: "~plugins/vimeo-player",
      ssr: false
    }
  ],

  build: {
    vendor: ["vue-vimeo-player"]
  }

```

template

```
      <vimeo-player
        video-id="67475783"
        player-width="640"
        player-height="360"
      ></vimeo-player>

```

plugins/vimeo-player.js

```
import Vue from 'vue'
import vueVimeoPlayer from 'vue-vimeo-player'

Vue.use(vueVimeoPlayer)
```

I basically followed the Nuxt guide in the readme and tried to plug this plugin in, everyhing should be default. Did I miss something?

**Comment by dobromir-hristov** [comment]
Is it working? I think that is normal because it wants to render the vimeo player just after the page has been rendered.

**Comment by Hurtak** [comment]
It is working but afaik it should just render empty shell, on the client it should validate that the html of the shell is the same and then on componentDidMoiunt (sry I am more react guy, not sure what the correct component lifecycle method is in vue) it should change the html.

**Comment by dobromir-hristov** [comment]
Try using the no-ssr component as in the docs

**Comment by Hurtak** [comment]
That seems to work, but I wonder why ssr: false in nuxt config was not enough.

**Comment by dobromir-hristov** [comment]
I think its because vimeo uses some of the global objects in the Window and that does some magic, I still have not used Nuxt in my daily workflow so I cant say for sure, but I saw that issue with other ppl's projects.
