### ISSUE TITLE
Missing SameSite attribute raises warning in Chrome

### ISSUE THREAD

**Issue by SableRaf** [dobromir-hristov/vue-vimeo-player#30]
`A cookie associated with a cross-site resource at http://vimeo.com/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by dobromir-hristov** [comment]
That is entirely up to Vimeo to fix mate, sorry.
