### ISSUE TITLE
Start playback at specific time

### ISSUE THREAD

**Issue by EvanAgee** [dobromir-hristov/vue-vimeo-player#33]
Thanks for the hard work!

I'm working on storing a users watch progress on a video and then when the page is revisited later the video will automatically start where they left off. I'm not seeing a way to do this, can you assist? Thanks!

**Comment by dobromir-hristov** [comment]
Hey, thanks.
Try accessing the player's API directly - `this.$refs.vimeo.player.setCurrentTime()` 
https://github.com/vimeo/player.js/#setcurrenttimeseconds-number-promisenumber-rangeerrorerror

**Comment by EvanAgee** [comment]
Thanks so much @dobromir-hristov , got it working!

**Comment by EvanAgee** [comment]
For anyone else you needs this later, here's what ended up working.

`this.$refs.player.player.setCurrentTime(this.videoProgress);`
