### ISSUE TITLE
Handle resize?

### ISSUE THREAD

**Issue by garyo** [dobromir-hristov/vue-vimeo-player#34]
I'm showing several videos in a `v-container` and trying to make it responsive. When I resize the window, my parent component changes the `player-width` and `player-height` props I'm passing into `vueVimeoPlayer` but it doesn't change size until I reload the page. Could the player either handle resize events, or respect when the incoming width/height props change and resize itself?

**Comment by dobromir-hristov** [comment]
This is a problem with the native Vimeo player.
You could use css to fix the issue? That's what most of us use to make responsive players. 
There should be a ticket explaining how exactly, or just google responsive iframes.
