### ISSUE TITLE
Do not define width and height

### ISSUE THREAD

**Issue by chou666** [dobromir-hristov/vue-vimeo-player#41]
In my case, I want to have the iframe with width="100%" and height="100%" ( or to be manage in CSS). But the width and height are sent to the player, the value id 100px

For backwards compatibility, defined width and height option of the player only if not null

**Comment by HarwinBorger** [comment]
Great component, compliments for that. 

I have the same issue as @chou666 mentioned, i would like to have no width/height set. 

And or those options would be nice: 
`player-width="100%"` player-height="100%"`
and / or 
`player-width="false"` player-height="false"` / `player-width=""` player-height=""`

**Comment by dobromir-hristov** [comment]
If not provided, the player will fallback to the max widht and height that the Video Supports, is that what you want?

**Comment by dobromir-hristov** [comment]
If you want a responsive player, you would have to do some CSS magic in any case, a bit of position absolute here and there and aspect ratios

**Comment by Mjavala** [comment]
setting the responsive option to true helped me solve this 
``:options="{responsive: true}"``

**Comment by chou666** [comment]
Many thanks to @Mjavala for yout tips !

This solve my problem:

`            vimeoOptions: {
                responsive: true,
                width: "1000",
                height: "100%",
            },
`

`
            <vue-vimeo-player
                :video-id="video"
                :video-url="video"
                :height="'100%'"
                :width="'100%'"
                :client-height="'100%'"
                :client-width="'100%'"
                :options="vimeoOptions"
            />
`
