### ISSUE TITLE
add responsive parameter

### ISSUE THREAD

**Issue by rafaelcruz-net** [dobromir-hristov/vue-vimeo-player#45]
Hello, 

As you can in this thread https://github.com/vimeo/player.js/issues/38, there a parameter to made the player responsive. 

Here a snippet of the code:

props: {
    playerHeight: {
      default: 320
    },
    playerWidth: {
      default: 640
    },
    options: {
      default: () => ({})
    },
    videoId: {
      required: true
    },
    videoUrl: {
      default: undefined
    },
    loop: {
      default: false
    },
    autoplay: {
      default: false
    },
    controls: {
      default: true
    },
    responsive: {
      default: false
    }
  },

 mounted () {
    const options = {
      id: this.videoId,
      width: this.playerWidth,
      height: this.playerHeight,
      loop: this.loop,
      autoplay: this.autoplay,
      controls: this.controls,
      responsive: this.responsive
    };
    if (this.videoUrl) { options.url = this.videoUrl; }

    this.player = new Player(this.elementId, assign(options, this.options));

    this.setEvents();
  },

**Comment by dobromir-hristov** [comment]
Cant you do:
```vue
<template>
  <vimeo-player ref="vimeo" v-bind="playerOptions"/>
</template>
<script>
export default {
    data() {
        return {
            playerOptions: {
                videoId: "videoID",
                playerWidth: undefined,
                playerHeight: undefined,
                options: {
                    responsive: true
                }
            }
        }
    }
}
</script>
```

**Comment by hamrant** [comment]
Tested code from https://github.com/dobromir-hristov/vue-vimeo-player/issues/45#issuecomment-631299943 - works fine, the issue can be closed.

@dobromir-hristov thanks!
