### ISSUE TITLE
Error to load video at first time

### ISSUE THREAD

**Issue by felipeminello** [dobromir-hristov/vue-vimeo-player#46]
If the video I try to load in the player is not available, I can no longer change the video using reactive variables of vue

**Comment by oolong32** [comment]
I encountered the same problem. The solution was moving the line `Vue.use(vueVimeoPlayer)` up, i.e. before `new Vue({ //… })`.

**Comment by dobromir-hristov** [comment]
Please provide reproduction examples, so we can propose a fix.
