### ISSUE TITLE
Is there a way to skip the video to a set position?

### ISSUE THREAD

**Issue by Mamotromico** [dobromir-hristov/vue-vimeo-player#5]
Something like player.seek(seconds)?

I know that the vimeo api supports this, but I couldn't find anything similar on this component.

Thanks!

**Comment by dobromir-hristov** [comment]
Well you have access to the instance so you could do `this.$refs.vimeoPlayer.player.seek(seconds)` there is no prop for it.

**Comment by Mamotromico** [comment]
Brilliant!
I was able to do a ``this.$refs.vimeoPlayer.player.setCurrentTime(seconds)``

Thanks!
