### ISSUE TITLE
Nuxt- App is not defined

### ISSUE THREAD

**Issue by vivekkairi** [dobromir-hristov/vue-vimeo-player#52]
So according to the docs, this is the way to create plugin in Nuxt
```
import Vue from 'vue'
import vueVimeoPlayer from 'vue-vimeo-player'

const app = Vue.createApp(App)
app.use(vueVimeoPlayer)
```

But it throws an error stating App is not defined. So, I went the traditional way and created a plugin in similar fashion
```
import Vue from 'vue'
import vueVimeoPlayer from 'vue-vimeo-player'

Vue.use(vueVimeoPlayer)
Vue.component(vueVimeoPlayer)
```
I got no errors but there's no element rendering inside the DOM
Here's the page code

```
<template>
  <div class="video">
    <client-only>
      <vimeo-player ref="player" :video-id="videoID" />
    </client-only>
  </div>
</template>

<script>
export default {
  data() {
    return {
      videoID: '48076xxxx',
    }
  },
}
</script>
```

And here's the DOM
![image](https://user-images.githubusercontent.com/15711742/101170483-8a4f1480-3664-11eb-98fd-84f090359456.png)

**Comment by dobromir-hristov** [comment]
Please use the master branch docs. The next branch is for Vue 3
