### ISSUE TITLE
loadVideo not called with options

### ISSUE THREAD

**Issue by dannywp** [dobromir-hristov/vue-vimeo-player#54]
on update the player.loadVideo method is called without options. Is this intended?

**Comment by dobromir-hristov** [comment]
I don't remember, what parameters do you want it to accept?

**Comment by dobromir-hristov** [comment]
I don't think we have that method. Is it a vimeo player method?

**Comment by dannywp** [comment]
![image](https://user-images.githubusercontent.com/59581112/106772049-ea9c0b80-663f-11eb-8621-50d056524c4b.png)

This one.

**Comment by dobromir-hristov** [comment]
Right, well, it accepts an object or id, so we are passing the ID. What is your use case?

**Comment by dannywp** [comment]
I have a video player with a series of videos. If a user sets captions to spanish fx. then when the next video in the series loads, the video isn't initialized with the options I have set which means I have to set the texttrack on every load.

You are initializing the player with options which is fine, but on update it is ignored.

**Comment by dobromir-hristov** [comment]
Can't argue with that. Would you like to make a PR?

**Comment by dannywp** [comment]
Yeah I would :)

**Comment by dannywp** [comment]
#55

**Comment by dobromir-hristov** [comment]
Fixed in 0c21bad519f7056c1e8d23cdead2746e252520dc
