### ISSUE TITLE
Controls prop

### ISSUE THREAD

**Issue by kovaletsyurii** [dobromir-hristov/vue-vimeo-player#57]
Does it possible to make **controls** prop reactive?

**Comment by eduardoliron** [comment]
If you are using Vue as your framewor, you should simply bind the controls option to a boolean variable

:controls="myControlsBooleanVar"

**Comment by kovaletsyurii** [comment]
@eduardoliron Yes I do this, but it doesn't work for me, I will try to create a reproduce repo

**Comment by kovaletsyurii** [comment]
@eduardoliron I use it like
`vimeo-player(
    ref="player"
    :video-id="videoID"
    :player-height="null"
    :controls="showVideoControls"
    @playing="onPlay"
    @play="onPlay"
    @pause="onPause"
    @ended="onEnded"
  )`
  
  and in my code I set this.showVideoControls = true, but player controls panel still not visible.

**Comment by eduardoliron** [comment]
You are right. I could reproduce the error.

**Comment by kovaletsyurii** [comment]
@eduardoliron Do you know a way to solve it? I've tried a few older versions of this library and I've reproduce this issue for all versions that I've tried.

**Comment by dobromir-hristov** [comment]
Should be fixed with `vue-vimeo-player@1.0.4` (0c21bad519f7056c1e8d23cdead2746e252520dc)
