### ISSUE TITLE
Programmatically control 360 VR videos

### ISSUE THREAD

**Issue by eduardoliron** [dobromir-hristov/vue-vimeo-player#58]
First of all, thank you for implementing the API for vue3.

I am working in a VR project and I was very glad to notice that I could easilly receive the spatial coordinates of the video by the @camerachange event.

I was wondering if it is possible to programmatically interact with the spatial coordinates as well somehow.

Thanks in advance.

**Comment by dobromir-hristov** [comment]
Probably using the player instance on the vimeo component?

Give me a link to the docs, and I can see what i can do

**Comment by eduardoliron** [comment]
I got the solution:
At the events-to-emit option there is a "camerachange" possibility. It was not documented though.

Thanks a lot!
