### ISSUE TITLE
vendor has been deprecated due to webpack4 optimization

### ISSUE THREAD

**Issue by delueg** [dobromir-hristov/vue-vimeo-player#62]
Hello, i get this warning when run `npm run dev` with nuxt.

_WARN  vendor has been deprecated due to webpack4 optimization_ 

can we safely omit `vendor: ['vue-vimeo-player'],` inside nuxt.config?

**Comment by dobromir-hristov** [comment]
I think you already know by now 😆 let me know if it works, so we can drop it from the docs.
