### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by JshGrn** [dobromir-hristov/vue-vimeo-player#63]
Hi there,

Used your plugin flawlessly throughout all my projects however having difficulty in settings options in a new Vue3 project.

VJS Devtools I can see that options are being passed correctly but it looks like they are not being passed to the player?

![image](https://user-images.githubusercontent.com/75624794/110028058-b1cc8080-7d2a-11eb-9714-20f2c6ee8435.png)

Responsive is not working, but I have tried a few options and it looks like none of them work...

Thank you,
Josh

**Comment by JshGrn** [comment]
It looks like options are not being passed down via mergeOptions, if I specify the options within ops they are passed to the player correctly.

**Comment by JshGrn** [comment]
Line 90 is returning opts without merging with props.options, could we change:

return opts;

to

return Object.assign(opts, props.options);

**Comment by dobromir-hristov** [comment]
Yep, I have just forgotten to do so. Please make a PR.

**Comment by JshGrn** [comment]
> Yep, I have just forgotten to do so. Please make a PR.

I am unable to do that at the minute but I will when I can

**Comment by dobromir-hristov** [comment]
Published

**Comment by JshGrn** [comment]
> Published

Excellent, thank you very much. Top man!
