### ISSUE TITLE
Play method doesn't work

### ISSUE THREAD

**Issue by nickforddesign** [dobromir-hristov/vue-vimeo-player#7]
I tried using the `autoplay` prop, which doesn't seem to work, then tried to use the `ready` event to manually call the `play` method, but the video does not play. I've included an example on codesandbox below.

https://codesandbox.io/s/r56674nznp

**Comment by dobromir-hristov** [comment]
It starts immediately for me. Are you trying on mobile or on desktop?

**Comment by dobromir-hristov** [comment]
https://github.com/vimeo/player.js/issues/242

**Comment by nickforddesign** [comment]
Thanks for the quick response, yes I'm using Chrome on desktop and that does seem to be the issue. It's unfortunate but I'm glad to know whats going on. I'll close the issue since it's browser level.
