### ISSUE TITLE
Local import and Lazy loading ?

### ISSUE THREAD

**Issue by ecwio** [dobromir-hristov/vue-vimeo-player#81]
Sorry if this is a noob question
I am trying to import the component locally as in the doc:

`  import { vueVimeoPlayer } from 'vue-vimeo-player'
  
  export default {
  	data: {},
  	components: { vueVimeoPlayer }
  }
`

I must precise I did not import globally with `Vue.use()` as it is not needed for me.

but `<vimeo-player>` is not found; nothing happens

I don't understand why

Vimeo is not going to be much on my website so I need:
- import locally
- lazy loading like `const vueVimeoPlayer = defineAsyncComponent(() => import ('vue-vimeo-player'))`

**Comment by dobromir-hristov** [comment]
The name of the component matches the one in your components.

<vue-vimeo-player> should for you

**Comment by ecwio** [comment]
@dobromir-hristov thank you for the support

my import is `    import { vueVimeoPlayer } from 'vue-vimeo-player'`
`components:{  vueVimeoPlayer }`

I tried 

         <vimeo-player
            v-if="videoType === 'vimeo'"
            ref="player"
            :video-id="getVimeoId(videoUrl)"
            :player-height="500"
        />

with this my IDE reports `Unknown html tag vimeo-player`; webpack reports the same when loading the page

and with

        <vueVimeoPlayer
            v-if="videoType === 'vimeo'"
            ref="player"
            :video-id="getVimeoId(videoUrl)"
            :player-height="500"
        />

nothing happens

`getVimeoId` is never triggered
