### ISSUE TITLE
player does not render

### ISSUE THREAD

**Issue by jrglaber** [dobromir-hristov/vue-vimeo-player#84]
I'm calling the player, but it's giving an error when rendering it. Below is the code: 

```
<template>
    <vue-vimeo-player ref="player" autoplay video-id="647004474" class="embeded-video" @ended="ended" @loaded="loaded" />
</template>

<script>
  import {vueVimeoPlayer} from 'vue-vimeo-player'
  export default {
    name: 'Video',
    components: {vueVimeoPlayer},
   }
</script>
```

The error that appears is the following:
![image](https://user-images.githubusercontent.com/1704179/144919261-531ef9b6-f85e-42e6-9ab3-505319fb463e.png)

**Comment by dobromir-hristov** [comment]
Can you provide a minimal example, that shows the error. The screenshot shows you are using it with quasar components.

**Comment by jrglaber** [comment]
The complete code follows. Before, I used the version compatible with vue2, but when I updated the application to vue3, I had the need to update the player, and it started to generate this error. This is a compinent from application:

```
<template>
  <v-modal v-model="showVideo" pageClass="bg-dark">
    <vue-vimeo-player ref="player" autoplay :video-id="video" class="embeded-video" @ended="ended" @loaded="loaded" />
  </v-modal>
</template>

<script>
  import {vueVimeoPlayer} from 'vue-vimeo-player'
  export default {
    name: 'Video',
    components: {vueVimeoPlayer},
    props: {
      modelValue: {
        type: String,
        required: true,
      },
      setVideo: {
        type: Boolean,
        default: true,
      }
    },
    data () {
      return {
        showVideo: false,
      }
    },
    computed: {
      video: {
        get: function() {
          return this.modelValue
        },
        set: function (newValue) {
          this.$emit('update:modelValue', newValue)
        }
      }
    },
    watch: {
      showVideo: function () {
        if(!this.showVideo && this.setVideo){
          this.$emit('update:modelValue', null)
        }
      }
    },
    methods: {
      ready: function (player) {
        console.dir(player)
      },
      loaded: function () {
        this.$refs.player.play()
      },
      ended: function () {
        this.showVideo = false
      }
    },
    created () {
      this.showVideo = true
    }
  }
</script>

<style lang="scss">
  .embeded-video{
    width: 100% !important;

    iframe{
      width: 100% !important;
      height: 100vh !important;
    }
  }
</style>
```

**Comment by dobromir-hristov** [comment]
Does this happen even without being wrapped in a quasar component? I need to know, if it's a bug with the component or integration with the quasar components.

**Comment by jrglaber** [comment]
This is a complete component. The quasar plugin dont access the component, but is parent component. But I'm going to test it without the Quasar in the parent component and I'll tell you.

**Comment by jrglaber** [comment]
I´m create the new vue project (without quasar) and worked.
 
I´m create the new quasar project and worked. 

Then... i realocate the video player in App.vue, deleting the project code, leaving only the player code,  leaving the clean code, but, the warning message continuous and dont render the player.

```
<template>
  <vue-vimeo-player ref="player" autoplay video-id="647004474" class="embeded-video" />
</template>
<script>
import { defineComponent } from 'vue';
import {vueVimeoPlayer} from 'vue-vimeo-player'
export default defineComponent({
  name: 'App',
  components: {vueVimeoPlayer},
})
</script>
```

In window console, is pointing in file plugin, but dont know.....

Tomorrow, I will reinstall the plugin to see if it works, otherwise I will have to use another alternative

![image](https://user-images.githubusercontent.com/1704179/144945407-4dfb24fe-7ac5-492c-8b3e-485b9f75c3b2.png)

![image](https://user-images.githubusercontent.com/1704179/144945329-4cb6f825-08b9-4c7f-afa7-1a99f0143f40.png)

![image](https://user-images.githubusercontent.com/1704179/144946055-2357727f-0210-499b-8785-e46555051f1b.png)

**Comment by dobromir-hristov** [comment]
Which version of Vue 3 does your current project use?

**Comment by jrglaber** [comment]
3.2.23

**Comment by dobromir-hristov** [comment]
If the new fresh project you created is using the same, then it must be something with your setup. Otherwise it may be some breaking change on the component transformation process, then I release a new build.

**Comment by jrglaber** [comment]
I'll keep analyzing to see if I can find the point where the break occurs, if I find something I'll let you know for an improvement.

**Comment by dobromir-hristov** [comment]
Going to close this for now, as I assume since time passed you figured it out.
