### ISSUE TITLE
Vue3 - Accessing underlying Vimeo player

### ISSUE THREAD

**Issue by swilla** [dobromir-hristov/vue-vimeo-player#85]
I'm trying to `setCurrentTime()` on a video, but I cannot access the underlying Vimeo player instance. 

`let player = this.$refs.vimeo;`

Gives me access to the `vueVimeoPlayer`, but If I do this: 

`let player = this.$refs.vimeo.player;`

This value is undefined. 

Is there a different way we need to set this up to in the `vue-vimeo-player@next`? 

![image](https://user-images.githubusercontent.com/304159/149337437-ed47328a-51ef-43e2-8054-2b7c245d19c0.png)

**Comment by dobromir-hristov** [comment]
Hey, sorry for the long wait. Did you manage to figure it out?

**Comment by nkeezer** [comment]
Just chiming in to say that I'm experiencing the same issue with accessing the player and calling setCurrentTime().

**Comment by dobromir-hristov** [comment]
I know why. We need to return the player from the setup function.

Anyone want to do a PR?

**Comment by swilla** [comment]
https://github.com/dobromir-hristov/vue-vimeo-player/pull/88

**Comment by PawDC** [comment]
Could this also be a reason why I don't see `on` method here:
<img width="1014" alt="Screenshot 2022-01-27 at 15 30 36" src="https://user-images.githubusercontent.com/98536823/151379151-b880843f-443e-4bad-8839-879fb5a5da83.png">

When I try to access it (same way I access `play` which works fine) it throws an error that `on` is not a function.

**Comment by pandalion** [comment]
Do you know when this will be released to npm please? I also need to access the `player` object to call `setCurrentTime`

**Comment by dobromir-hristov** [comment]
I am extremely sorry, I totally forgot.... I will release this night.

**Comment by JamieNuom** [comment]
I am also waiting on this, can you update when released? Thanks!

**Comment by dobromir-hristov** [comment]
Published, sorry all. Try the latest `next`  - 1.1.2

**Comment by pandalion** [comment]
Thank you @dobromir-hristov !

**Comment by pandalion** [comment]
Hi @dobromir-hristov - I have tried the new version and when I am logging `this.$refs.vimeo.player` I am still getting `undefined` for the player.

`this.$refs.vimeo.pause()` is working fine, and the rest of the player, but my problem is still when trying to use `setCurrentTime()`. 

Please could you advise if this is something I am doing wrong on my end? Does 1.1.2 work now for you @JamieNuom ?

Thank you :)

**Comment by timmyomahony** [comment]
Also experiencing this with the composition API (using Vue 3 with `1.1.2`):

```
<template>
  <vue-vimeo-player ref="player" video-url="..." :options="..." />
</template>

<script setup>
  import { vueVimeoPlayer } from 'vue-vimeo-player';
  
  const player = ref(null);

  // Works
  player.value.play();
  player.value.pause();

  // Is undefined
  player.value.player;
</script>
```

**Comment by timmyomahony** [comment]
@pandalion here is my hack for getting this working in the meantime. I've created an event listener for "ready" that re-assigns the vimeo player instance:

```
<template>
  <vue-vimeo-player ref="player" video-url="..." :options="..." @ready="onReady" />
</template>

<script setup>
  import { vueVimeoPlayer } from 'vue-vimeo-player';
  
  const player = ref(null);

  const onReady = (_playerInstance) => {
    player.value.player = _playerInstance;
  }
</script>
```

**Comment by pandalion** [comment]
@timmyomahony thank you so much for that!

**Comment by Joaojack** [comment]
> const onReady = (_playerInstance) => {
>     player.value.player = _playerInstance;
>   }

you saved me man ;)
