### ISSUE TITLE
Compile warnings

### ISSUE THREAD

**Issue by OctaneInteractive** [dobromir-hristov/vue-vimeo-player#97]
Hi, I've tried both import methods but I'm getting the same warnings from `npm run dev`:

> WARNING  Compiled with 14 warnings                                                                                                                                                             11:23:44
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 125:4-13 "export 'onMounted' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 132:4-19 "export 'onBeforeUnmount' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 135:4-9 "export 'watch' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 140:4-9 "export 'watch' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 145:10-15 "export 'toRef' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 145:4-9 "export 'watch' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 174:22-40 "export 'createElementBlock' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 174:9-18 "export 'openBlock' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 61:21-24 "export 'ref' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 63:18-24 "export 'toRefs' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 82:10-15 "export 'unref' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 83:19-24 "export 'unref' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 86:10-15 "export 'unref' was not found in 'vue'
> 
>  warning  in ./node_modules/vue-vimeo-player/dist/index.es.js
> 
> 87:18-23 "export 'unref' was not found in 'vue'

In the client, I get the same warnings but with additional information (I could share, if required, but it is a _lot_), followed by the warning:

> [Vue warn]: Unknown custom element: <vimeo-player> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

The code is correct:

`<vimeo-player :video-id="assetOfInterest.attributes[0].mediaItemAddress[1]"></vimeo-player>`

```
// Twitter.
import { Timeline, Tweet } from 'vue-tweet-embed'
import { vueVimeoPlayer } from 'vue-vimeo-player'
// Mixins.
import { StateManagement } from '../../../mixins/StateManagement'
export default {
  name: 'AssetMedia',
  components: {
    Timeline,
    Tweet,
    vueVimeoPlayer
  } ...
```

I'm using Vue 2.5.2

**Comment by OctaneInteractive** [comment]
I've since seen this package is for Vue 3 not 2 — feel free to delete!

**Comment by dobromir-hristov** [comment]
Use the other branch for Vue 2
